### ISSUE TITLE
FATAL/BACKOFF Exited too quickly (process log may have details)

### ISSUE THREAD

**Issue by AloisJasa** [peckadesign/Supervisor#17]
Pokud proces, který supervisor měl udržet na živu) proběhne moc rychle, tak to supervisor považuje za chybu, označí se jako FATAL a už se dál nesnaží proces opětovně spustit.
Typicky když má supervisor držet nějakého rabbitího consumera, který má nastaveno zpracovat málo zpráv a všechny projde hrozně rychle. 

Podle internetu je mezní hodnota 1s což odpovídá i našim zkušenostem. 
Tohle by mělo řešit natavení `startsecs=0`, které má defaultní hodnotu na 1s.

**Comment by tomasfoltyn** [comment]
Imho se to typicky objeví, když tam máš nějakou chybu, kvůli které ten consumer ani nestačí naběhnout

**Comment by tomasfoltyn** [comment]
A nastavit pro konkrétní proces to jde už teď - https://github.com/peckadesign/Hudy2017/pull/5574/commits/280ed400b66d6bad4c40bd41db694fca13420e67

**Comment by AloisJasa** [comment]
> Imho se to typicky objeví, když tam máš nějakou chybu, kvůli které ten consumer ani nestačí naběhnout

Taky, ale dělá to i když je nastaven malý počet zpráv ke zpracování a consumer je jen prolítne. 

> A nastavit pro konkrétní proces to jde už teď - https://github.com/peckadesign/Hudy2017/commit/280ed400b66d6bad4c40bd41db694fca13420e67

To jsem nevěděl. Jelikož o tom v Pecce nikdo nemluvil, tak jsem měl za to, že to neumíme.
Škoda, že nechodíš na standupy. :-)

**Comment by AloisJasa** [comment]
Probrali jsme to a stačí nám nastavit `startsecs=0` u konkrétních procesů. 

Proto aktuálně nepotřebujeme globální řešení/nastavení a nebudeme zde tedy nic upravovat, issue zavírám.
Pokud by přeci jen bylo v budoucnosti něco takového potřeba, lze vycházet z tohoto issue. 

Děkuji @tomasfoltyn 👍
